---
abstract: 'A client implementation of the ICAP (RFC 3507) protocol'
author:
  - 'David Dick <ddick@cpan.org>'
build_requires:
  File::Temp: '0'
  HTTP::Headers: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-ICAP-Client
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  English: '0'
  HTTP::Request: '0'
  HTTP::Response: '0'
  IO::Socket::INET: '0'
  IO::Socket::SSL: '0'
  POSIX: '0'
  URI: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
version: '0.08'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
